CREATE DATABASE DETHITHUSO2
USE DETHITHUSO2
CREATE TABLE SACH
(
	MaSach char(5),
	TenSach varchar(20),
	TheLoai varchar(50),
	NXB varchar(20)
	CONSTRAINT PK_SACH PRIMARY KEY (MaSach)
)
CREATE TABLE KHACHHANG
(
	MaKH char(5),
	HoTen varchar(25),
	NgaySinh smalldatetime,
	DiaChi varchar(50),
	SoDT Varchar(15),
	NgDK Smalldatetime,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MaKH)
)
CREATE TABLE CHITIET_PHIEUTHUE
(
	MaSach char(5),
	MaPT char(5)
	CONSTRAINT PK_CHITIET_PHIEUTHUE PRIMARY KEY (MaSach,MaPT)
)
CREATE TABLE PHIEUTHUE
(
	MaPT char(5),
	MaKH Char(5),
	NgayThue smalldatetime,
	NgayTra smalldatetime,
	SoSachThue int,
	CONSTRAINT PK_PHIEUTHUE PRIMARY KEY (MaPT)
)
ALTER TABLE CHITIET_PHIEUTHUE ADD CONSTRAINT FK_CHITIET_PHIEUTHUE FOREIGN KEY (MaSACH) REFERENCES Sach(MaSach)
ALTER TABLE CHITIET_PHIEUTHUE ADD CONSTRAINT FK_CHITIET_PHIEUTHUE1 FOREIGN KEY (MaPT) REFERENCES PHIEUTHUE(MaPT)
ALTER TABLE PHIEUTHUE ADD CONSTRAINT FK_PHIEUTHUE FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)

-- Câu 3:
-- Cho biết thông tin sách (MaSach,TenSach,TheLoai) được khách hàng thuê vào tháng 7 năm 2022? (1đ)
SELECT SACH.MaSach, TenSach, TheLoai
FROM SACH, CHITIET_PHIEUTHUE, PHIEUThUE
WHERE SACH.MaSach = CHITIET_PHIEUTHUE.MaSACH  AND CHITIET_PHIEUTHUE.MAPT = PHIEUTHUE.MAPT
AND MONTH(NgayThue) = 7 AND YEAR(NgayThue) = 2022
-- Cho biết thông tin khách hàng (MaKH, HoTen, SoDT) đã thuê sách thuộc thể loại “Tin học” trong năm 2022?
Select KHACHHANG.MaKH, HoTen, SoDT
From KhachHang, SACH, CHITIET_PHIEUTHUE, PHIEUThUE
Where SACH.MaSach = CHITIET_PHIEUTHUE.MaSACH  AND CHITIET_PHIEUTHUE.MAPT = PHIEUTHUE.MAPT AND KHACHHANG.MAKH = PHIEUTHUE.MAKH
AND theloai ='Tin hoc' AND YEAR(NgayThue) = 2022 

-- Cho biết số lượng sách của từng thể loại được thuê trong năm 2022. Thông tin hiển thị bao gồm: Thể loại, số lượng sách? (1đ)
SELECT THELOAI, COUNT(SACH.MASACH)
From KhachHang, SACH, CHITIET_PHIEUTHUE, PHIEUThUE
Where SACH.MaSach = CHITIET_PHIEUTHUE.MaSACH  AND CHITIET_PHIEUTHUE.MAPT = PHIEUTHUE.MAPT AND KHACHHANG.MAKH = PHIEUTHUE.MAKH AND YEAR(NgayThue) = 2022 
GROUP BY THELOAI
-- Cho biết thông tin sách (MaSach, TenSach, TheLoai) không được thuê trong năm 2022? (1đ)
SELECT SACH.MASACH, TenSACh, THeLoai
From SACH WHERE MASACH NOT IN(
SELECT SACH.MASACH
From KhachHang, SACH, CHITIET_PHIEUTHUE, PHIEUThUE
Where SACH.MaSach = CHITIET_PHIEUTHUE.MaSACH  AND CHITIET_PHIEUTHUE.MAPT = PHIEUTHUE.MAPT AND KHACHHANG.MAKH = PHIEUTHUE.MAKH AND YEAR(NgayThue) = 2022 )
-- Tìm khách hàng (MaKH, HoTen) đã thuê nhiều thể loại sách nhất? 
SELECT TOP 1 KHACHHANG.MaKH, HoTen 
From KhachHang, SACH, CHITIET_PHIEUTHUE, PHIEUThUE
Where SACH.MaSach = CHITIET_PHIEUTHUE.MaSACH  AND CHITIET_PHIEUTHUE.MAPT = PHIEUTHUE.MAPT AND KHACHHANG.MAKH = PHIEUTHUE.MAKH
GROUP BY KHACHHANG.MaKH, HoTen 
ORDER BY COUNT(SACH.MaSACh) DESC 